version: 1
build:
  main: cmd/mineplex-chaind
  proto:
    path: ""
    third_party_paths: []
accounts:
- name: alice
  coins:
  - 100000000000000000000mpx
- name: bob
  coins:
  - 100000mpx
  - 100000xfi
faucet:
  name: bob
  coins:
  - 100000mpx
  - 100000xfi
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: mpx
    gov:
      deposit_params:
        min_deposit:
        - amount: "1000000000000000000"
          denom: mpx
    staking:
      params:
        bond_denom: mpx
        max_validators: 64
        unbonding_time: 1296000s
    treasury:
      params:
        owner: mx1d0ga6s7ue244rep5z7gnmgeyf3ejzla0hggf0f
validators:
- name: alice
  bonded: 100000000000000000000mpx
