version: 1
genesis:
  app_state:
    staking:
      params:
        bond_denom: "mine2"
        unbonding_time: "1296000s"
        max_validators: 64
    crisis:
      constant_fee:
        denom: "mine2"
    gov:
      deposit_params:
        min_deposit:
        - denom: "mine2"
          amount: "1000000000000000000"
    treasury:
      params:
        owner: "mp1d0ga6s7ue244rep5z7gnmgeyf3ejzla0aw5rur"
accounts:
- name: alice
  coins:
  - 1000000mine2
- name: bob
  coins:
  - 100000mine2
  - 100000plex2
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000mine2
  - 100000plex2
validators:
- name: alice
  bonded: 1000000mine2
