version: 1
build:
  main: cmd/mineplex-chaind
genesis:
  app_state:
    staking:
      params:
        bond_denom: "mpx"
        unbonding_time: "1296000s"
        max_validators: 64
    crisis:
      constant_fee:
        denom: "mpx"
    gov:
      deposit_params:
        min_deposit:
        - denom: "mpx"
          amount: "1000000000000000000"
    treasury:
      params:
        owner: "mp1d0ga6s7ue244rep5z7gnmgeyf3ejzla0aw5rur"
accounts:
- name: alice
  coins:
  - 1000000mpx
- name: bob
  coins:
  - 100000mpx
  - 100000xfi
client:
  openapi:
    path: api-docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000mpx
  - 100000xfi
validators:
- name: alice
  bonded: 1000000mpx
