binary: "mineplex-chaind"
home_dir: "./chain_data"
keyring_backend: "file"
seed:
  name: "seed"
  addr: "seed-v2.mineplex.io:26656"
  client:
    keyring-backend: file
    broadcast-mode: block
  app:
    api:
      enable: true
  config:
    p2p:
      allow_duplicate_ip: true
    rpc:
      pprof_laddr: ""
      laddr: "tcp://0.0.0.0:26657"
genesis:
  chain_id: "mineplex-mainnet-1"
  genesis_time: "2023-03-30T08:30:00.000000Z"
  app_state:
    crisis:
      constant_fee:
        amount: "1000000000000000000000"
        denom: mpx
    distribution:
      base_proposer_reward: "0.000000000000000000"
      bonus_proposer_reward: "0.000000000000000000"
      community_tax: "0.000000000000000000"
    gov:
      deposit_params:
        min_deposit:
          - amount: "1000000000000000000000"
            denom: mpx
      voting_params:
        voting_period:
          172800s
    staking:
      params:
        bond_denom: mpx
        max_validators: 64
        unbonding_time: 1296000s
    treasury:
      params:
        owner: mx1anctd79de6ry2m0u2va9x8tcls9jeflhg3r6ys
validators:
  - name: validator1
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator2
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator3
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator4
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator5
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator6
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator7
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator8
    bonded: 500000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      rpc:
        laddr: ""
        pprof_laddr: ""
    app:
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false